use_default_settings: true

server:
  secret_key: "aide-local-search-secret"
  limiter: false
  image_proxy: false

ui:
  static_use_hash: true

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json
